# Generated by Django 3.2.9 on 2022-08-11 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('password', models.CharField(blank=True, max_length=20, null=True)),
                ('user_user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(blank=True, max_length=10, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=5, null=True)),
                ('full_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_id', models.CharField(blank=True, max_length=10, null=True)),
                ('sub_name', models.CharField(blank=True, max_length=40, null=True)),
                ('faculty_faculty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('is_present', models.BooleanField(default=False)),
                ('student_student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.student')),
                ('subject_subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Main.subject')),
            ],
            options={
                'unique_together': {('subject_subject_id', 'student_student_id')},
            },
        ),
    ]
