# Generated by Django 3.2.9 on 2022-08-11 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_student_id',
            new_name='student_id',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='subject_subject_id',
            new_name='subject_id',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='user_user_id',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='faculty_faculty_id',
            new_name='faculty_id',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('subject_id', 'student_id')},
        ),
    ]
