# Generated by Django 3.2.9 on 2022-08-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20220811_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='subject_id',
            new_name='subject',
        ),
        migrations.RenameField(
            model_name='faculty',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='faculty_id',
            new_name='faculty',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('subject', 'student')},
        ),
    ]
