# Generated by Django 3.2.9 on 2022-08-11 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20220811_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Main.faculty'),
        ),
    ]
