# Generated by Django 3.2.9 on 2022-08-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_alter_subject_faculty'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('date', 'subject', 'student')},
        ),
    ]
