# Generated by Django 3.2.9 on 2022-11-12 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_qr_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qr_code',
        ),
    ]
