# Generated by Django 3.2.9 on 2022-11-17 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_delete_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='password',
        ),
    ]
